### ISSUE TITLE
Labels of vocabularies

### ISSUE THREAD

**Issue by filip-kopecky** [datagov-cz/showit#34]
In some cases the vocabulary names are the exact same. For now we don't show the same IRI labels twice, but this happens, when IRIs are different but names are the same
![image](https://user-images.githubusercontent.com/46053137/136342000-288c3465-0d5c-4cdd-afa4-95b9fdd9ff6b.png)

**Comment by FilipKopecky** [comment]
Okay, it looks like the data is wrong. TermIt doesn't allow for name duplicities
